# Generated by Django 5.0.6 on 2024-09-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentmodel",
            name="name",
        ),
        migrations.AlterField(
            model_name="documentmodel",
            name="title",
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
